version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: wallet
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: y_lab
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: